# Generated by Django 3.0.8 on 2020-08-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_summery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='summery',
        ),
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
    ]
