# Generated by Django 3.0.8 on 2020-08-31 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200831_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_part_2',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='body_part_3',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='media/blog_img/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='media/blog_img/'),
        ),
        migrations.AddField(
            model_name='post',
            name='secondary_title_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='secondary_title_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
