# Generated by Django 3.0.8 on 2020-09-01 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200901_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body_part_1',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='image_1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='body_part_2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='body_part_3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='secondary_title_1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='secondary_title_2',
        ),
    ]
