# Generated by Django 3.0.8 on 2020-09-01 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200901_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='primary_title',
            new_name='title',
        ),
    ]
