# Generated by Django 3.0.8 on 2020-09-06 12:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0013_comment_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('author', 'date_published')},
        ),
    ]
